### ISSUE TITLE
How to save & restart from a state?

### ISSUE THREAD

**Issue by umgupta** [pytorch/opacus#117]
## 📚 Documentation

I would like to understand how to save the state of the Privacy Engine and restart it from a saved state so that privacy spent is tracked properly.

**Comment by Darktex** [comment]
Excellent point. Unfortunately we don't currently support an API to do this just yet, but we are going to add it!

For the time being, I'd look into pickling the whole object and seeing what happens :D

**Comment by umgupta** [comment]
Thanks for the response. I will keep the issue open and shall try to contribute when I figure it out. For now, I will just do as you said.

**Comment by alexandresablayrolles** [comment]
Closing the issue as there are a state_dict() and a get_state_dict() method in the PrivacyEngine.
