### ISSUE TITLE
Opacus crashes when using DPLSTM

### ISSUE THREAD

**Issue by touqir14** [pytorch/opacus#134]
## 🐛 Bug

Running the following code snippet with the python interpreter causes a segmentation fault:
```python
from opacus.layers import DPLSTM
from opacus import PrivacyEngine
import torch 
from torch import nn

def foo():

  data = torch.rand(3,5,2)

  dp_lstm = DPLSTM(input_size=2, hidden_size=3, batch_first=True)
  optimizer = torch.optim.SGD(dp_lstm.parameters(), lr=0.1, momentum=0)
  criterion = nn.MSELoss()

  output, (hn, cn) = dp_lstm(data)
  y = torch.zeros_like(output[0])
  loss = criterion(output[0], y)
  loss.backward()

for i in range(10):
  foo()
```
This was tested with **Opacus 0.11 and python 3.9**. You will see the segmentation fault if you (1) save this into a python script and run it from the shell with the python interpreter OR (2) copy and paste this snippet into a python/ipython interpreter and then once you type exit/quit() . I am not sure where the memory error is coming from but this does highlight a bug at the core (possibly the way torch and opacus are interfaced). Or it could just be a torch issue. 

This also happens if the privacy engine is used.
## Environment

```
Collecting environment information...
PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Linux Mint 20 (x86_64)
GCC version: (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 440.100
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.1+cpu
[pip3] torchvision==0.8.2+cpu
[conda] Could not collect
```

**Comment by ffuuugor** [comment]
Thanks for reporting, that's indeed interesting.
I was able to reproduce it on python3.9. Works fine with 3.6.9 though.
It seems to me, that the issue might be in pytorch land, not opacus land - I'm still getting the same segfault after replacing DPLSTM with nn.LSTM

**Comment by Darktex** [comment]
My money is on Python 3.9 support in current PyTorch. 

The note on pytorch.org says you should install it differently for 3.9:

```
NOTE: Python 3.9 users will need to add '-c=conda-forge' for installation
conda install pytorch torchvision torchaudio -c pytorch
# MacOS Binaries dont support CUDA, install from source if CUDA is needed
```
