### ISSUE TITLE
Pytest as a runtime dependency

### ISSUE THREAD

**Issue by JMMarchant** [pytorch/opacus#142]
## 🐛 Bug

`pytest` is listed as a runtime requirement causing it to be installed as a subdependency when `opacus` is installed even if the end-user has no intention of running the tests. This has the knock-on effect of causing `pytest` to become a dependency for any later project that uses a library that uses `opacus`.

## To Reproduce

1. Run `pip install opacus`.
2. Run `pip list`.
3. See that `pytest` has been installed.

## Expected behavior

Unless it's needed by the runtime library functions there shouldn't be a need to install `pytest` for the average end-user.

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.2 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect

**Comment by Darktex** [comment]
Great point @JMMarchant ! We will move pytest to the dev installation. Thank you!
