### ISSUE TITLE
PyTorch Lightning issues with gradients not being detected properly

### ISSUE THREAD

**Issue by JMMarchant** [pytorch/opacus#147]
## 🐛 Bug

When trying to use PyTorch Lightning to create models, the `PrivacyEngine` fails due to `AttributeError: The following layers do not have gradients` despite the layers being included, implicitly, in the backward pass.

## Please reproduce using our [template Colab](https://colab.research.google.com/drive/1pCyN3_gN3WyhyQt8--eBPN5zVf2XZxiN?usp=sharing) and post here the link
https://colab.research.google.com/drive/1dLTMS7wZFD-43RNm1vdfW2umFkSTzfVB?usp=sharing

## Expected behavior

The backward pass used by PyTorch Lightning should work with the `opacus` `PrivacyEngine` hooks in the optimizer.

## Additional context

I have found this bug occurs across multiple environments (Colab, macOS, Ubuntu) and multiple PyTorch versions (1.6, 1.7.1)

**Comment by sayanghosh** [comment]
@JMMarchant Thanks for filing this bug report, I believe it is related to the earlier issue https://discuss.pytorch.org/t/pytorch-lightning-support/113507.  We will be looking into Lightning integration with Opacus using this bug  you filed.
