### ISSUE TITLE
About reported DP in mnist example

### ISSUE THREAD

**Issue by zliangak** [pytorch/opacus#153]
Hi, I have just run the MNIST example and used the parameter in mnist_README.md file. 
```
python mnist.py --device=cpu -n=15 --lr=.25 --sigma=1.3 -c=1.5 -sr=0.004
```
And I notice that the final epsilon is 1.16, not 1.19 reported in the mnist_README.md file. And this problem happens to another parameter recommendation.  For 
```
-n=45 --lr=.25 --sigma=.7 -c=1.5 -sr=0.004
```
epsilon should be 6.859. And for 
```
-n 60 --lr=.15 --sigma=1.1 -c=1.0 -sr=0.004
```
epsilon should be 2.905.

**Comment by ashkan-software** [comment]
Hello!

Thank you for bringing this up into our attention. We are looking into this :)
