### ISSUE TITLE
From RDP to (epsilon, delta)-DP

### ISSUE THREAD

**Issue by mmalekzadeh** [pytorch/opacus#157]
Hi,

There is a better conversion from RDP to (epsilon, delta)-DP than the current implementation which is a very important aspect of this library. So, here I explain it and suggest using the new formula. Unless there is something else that I am not aware of it. I appreciate your feedback.

**Explanation:**

Currently, the computed epsilon from RDP to (epsilon, delta)-DP is this line:

https://github.com/pytorch/opacus/blob/244265582bffbda956511871a907e5de2c523d86/opacus/privacy_analysis.py#L298

That is based on Proposition 3 in the main RDP paper: https://arxiv.org/abs/1702.07476

However, in the following paper (AISTATS 2019): https://arxiv.org/pdf/1905.09982.pdf
and in Theorem 21, the authors provide a better conversion from RDP to DP.

a (lazy) code for this better conversion will be something like this:
```
term_1 = np.array([math.log((alpha-1)/alpha) for alpha in orders_vec])
term_2 = np.array([math.log(alpha) for alpha in orders_vec])
eps = rdp_vec + term_1 - (math.log(delta)+term_2) / (orders_vec - 1)
```

As this new analysis provides us a better bound (i.e. smaller epsilons), it should be more useful to the users of Opacus.

Best

**Comment by ilyamironov** [comment]
Mohammad,

Thank you for flagging this! Although the savings are very modest in most practical regimes, why not use the most efficient conversion available?

If you feel up for it, how about you create a pull request that implements the change? We'd be glad to review it and check it in. A warning though - as usual, the most laborious part is not the main code, but rather the tests (and readme files).

**Comment by mmalekzadeh** [comment]
Thanks Ilya, for the confirmation.  I'm happy to do this pull request.
