### ISSUE TITLE
`opacus.layers.DPLSTM` has different default keyword arguments compared to `torch.nn.LSTM`

### ISSUE THREAD

**Issue by lxuechen** [pytorch/opacus#173]
## 🐛 Bug

`opacus.layers.DPLSTM` has slightly different default keyword arguments compared to `torch.nn.LSTM`. This inconsistency could create issues when one doesn't specify all argument explicitly. 

For instance, `torch.nn.LSTM` set `batch_first=True`, whereas `opacus.layers.DPLSTM` sets `batch_first=False`.

**Comment by alexandresablayrolles** [comment]
Thanks @lxuechen for raising this issue! Can you send a PR? If not, we will take care of it early next week.

**Comment by lxuechen** [comment]
Sorry, false alarm. I just double checked, the kwargs have the same default values.
