### ISSUE TITLE
Gradient per example before and after clipping

### ISSUE THREAD

**Issue by AliShahin** [pytorch/opacus#183]
Hello,

I wonder if there is an option to access the per example gradient before and after clipping during the training  please?

Thanks,
Ali

**Comment by ashkan-software** [comment]
Hi,

Thank you for your question! We don't answer questions or provide support via Github issues.

Could you please post this question on Pytorch forums with the category "Opacus"? (https://discuss.pytorch.org/c/opacus/29)

We will be happy to help - we actively monitor the forums.

Thanks
