### ISSUE TITLE
Improve RDP to (epsilon, delta)-DP conversion

### ISSUE THREAD

**Issue by lxuechen** [pytorch/opacus#186]
Tensorflow privacy has recently upgraded their RDP to (epsilon, delta)-DP conversion, i.e., see this [`_compute_eps`](https://github.com/tensorflow/privacy/blob/5f07198b66b3617b22609db983926e3ba97cd905/tensorflow_privacy/privacy/analysis/rdp_accountant.py#L237) function and their documentation for more. 

What this implies is that even though now opacus and tf_privacy both return the same RDP with a fixed set of input parameters, the eventual converted epsilons will not be the same, with the latter one being a lot smaller in some cases. For instance, 
```python
from opacus import privacy_analysis
import tensorflow_privacy as tf_privacy

orders = list(range(11, 64))

num_samples = 50000
batch_size = 1024
num_steps = 1464
target_delta = 1e-5
noise_multiplier = 1.54
sample_rate = batch_size / float(num_samples)

rdp = tf_privacy.compute_rdp(
    q=sample_rate, noise_multiplier=noise_multiplier, steps=num_steps, orders=orders
)
eps, delta, alpha = tf_privacy.get_privacy_spent(
    orders=orders, rdp=rdp, target_delta=target_delta
)
print(eps, delta, alpha)

rdp = privacy_analysis.compute_rdp(
    q=sample_rate, noise_multiplier=noise_multiplier, steps=num_steps, orders=orders
)
eps, alpha = privacy_analysis.get_privacy_spent(
    orders=orders, rdp=rdp, delta=target_delta
)
print(eps, alpha)
```
This code example gives the following outputs
```bash
2.8223025762413374 1e-05 11
3.1574022833254873 11
```

I'm not sure whether improving the privacy accounting as such is on the agenda, but if any of the maintainers here think this is a reasonable thing to work on, I'm happy to later send in a PR to help out (and this should only be a small change).

**Comment by ffuuugor** [comment]
Thanks for opening the issue!
As a matter of fact, we have already implemented this approach - see #167 
The problem is we haven't had a release since March, so the version you get from `pip install` is quite old. Our bad, new release is coming soon.

In the meantime you can do 
```
pip install git+git://github.com/pytorch/opacus.git@e0b8c676ffbfea9050a46370db3a8b5c56c08e9b
```

I got the same eps as `tf_privacy` with the latest code
