### ISSUE TITLE
Question about Oversampling

### ISSUE THREAD

**Issue by YongGuCheng** [pytorch/opacus#198]
## ❓ Questions and Help

Hi All,

For an imbalanced dataset, can we first use oversampling to balance the two classes, and then use Opacus for DP training over the artificially balanced dataset?

**Comment by ffuuugor** [comment]
Hi,
Thank you for your question, but we don't answer questions or provide support via github issues.

Please post any questions on Pytorch forums with the category "Opacus" (https://discuss.pytorch.org/c/opacus/29) and we'll be happy to help - we actively monitor the forums.

Thanks
