### ISSUE TITLE
GRU support for Opacus

### ISSUE THREAD

**Issue by ashkan-software** [pytorch/opacus#206]
## 🚀 Feature
GRU support for Opacus

## Motivation

Opacus currently does not support [Gated Recurrent Unit (GRU)](https://en.wikipedia.org/wiki/Gated_recurrent_unit). Looks like some of the members of the community are intersted in such feature. See, for example, [issue 205](https://github.com/pytorch/opacus/issues/205)

## Additional context

Supporting GRU in Opacus is a similar effort like [supporting LSTM](https://github.com/pytorch/opacus/commit/2ddd270d3ff637be6cd59c9f1e6cd860b29a6c5a) in Opacus. As maintainers of Opacus we didn't implement GRU so far mostly because nobody asked and there was no need. However, this is a good feature. We hope that one day this feature jumps to the top of our priorities so we can implement it. Or even better, maybe a contributor can send us a PR for this and we gladly work with them to support it! :)

**Comment by romovpa** [comment]
Hi, I'm happy to help with this.

**Comment by ffuuugor** [comment]
Good luck!

**Comment by ashkan-software** [comment]
Thanks @romovpa  for doing this! 

CC @anik123

**Comment by anik123** [comment]
Thanks @romovpa it would be a great help!

**Comment by romovpa** [comment]
There is some progress [here](https://github.com/romovpa/opacus/pull/1). 
I've created dirty but working replacements for `nn.GRU` and `nn.RNN`. Some work is to be done to merge LSTM code with RNN/GRU (presence of the cell state `c_n` in LSTM makes it tricky), update all tests. Then I'll update examples/tutorials in a separate diff.

We have `DPGRU` and `DPRNN` layers, the parametrized part of which is based on `RNNLinear` (former `LSTMLinear`).  
For `RNNLinear` we use aggregating grad sampler which sums out the sequence dimension. My understanding is that this is enough for PrivacyEngine to work correctly. Correct me here if wrong, please.

**Comment by ffuuugor** [comment]
Wow, that is some seriously impressive work! 
I've skimmed through your draft and on a high level it looks right about how it should be looking.

It's great that you've managed to bring together some of the common parts with DPLSTM implementation under the same base class (at least for the cells)

> My understanding is that this is enough for PrivacyEngine to work correctly.

That is my understanding as well: using only `RNNLinear` should do the trick. Anyways, the best way to be certain about this is to expand grad sampler test (`opacus/tests/grad_samples/dp_lstm_test.py`)

**Comment by ffuuugor** [comment]
All merged now, thanks @romovpa !

**Comment by anik123** [comment]
@romovpa Thanks for your effort. Sorry for the inconvenience.
