### ISSUE TITLE
`random_number_generator` is not moved to the target device

### ISSUE THREAD

**Issue by volltin** [pytorch/opacus#263]
## 🐛 Bug

`PrivacyEngine.to(device)` may confuse the user. 

If the `privacy_engine` is initialized with a model on CPU, `random_number_generator` is not moved to target device after calling `model.to(device)` and `privacy_engine.to(device)`, which will cause an error in `_generate_noise()`.

## Please reproduce using our [template Colab](https://colab.research.google.com/drive/1pCyN3_gN3WyhyQt8--eBPN5zVf2XZxiN?usp=sharing) and post here the link

https://colab.research.google.com/drive/1j_hFuyh97WBE8J94KfWop-fCZK0SNdV9?usp=sharing

## To Reproduce

1. Install PyTorch and opacus.
2. Run the code: https://gist.github.com/volltin/9b73390afe31b393f5a434b0cd685dd3.
3. Errors occurred because `privacy_engine.random_number_generator` did not move to GPU.

```
Traceback (most recent call last):
  File "/home/user/main.py", line 21, in <module>
    optimizer.step()
  File "/anaconda/envs/opacus-test/lib/python3.9/site-packages/opacus/privacy_engine.py", line 330, in dp_step
    self.privacy_engine.step(is_empty)
  File "/anaconda/envs/opacus-test/lib/python3.9/site-packages/opacus/privacy_engine.py", line 474, in step
    noise = self._generate_noise(clip_value, p)
  File "/anaconda/envs/opacus-test/lib/python3.9/site-packages/opacus/privacy_engine.py", line 577, in _generate_noise
    return torch.normal(
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```

## Expected behavior

Privacy Engine should move its random number generator to the target device after calling `.to(device)`.

## Environment

 - PyTorch Version: 1.10.0
 - OS: Ubuntu 18.04.6 LTS (x86_64)
 - How you installed PyTorch: `conda`
 - Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
 - CUDA/cuDNN version: CUDA used to build PyTorch: 11.3
 - GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
 - Any other relevant information: opacus==0.14.0

**Comment by alexandresablayrolles** [comment]
Thanks for flagging this issue. I believe it has been fixed in the latest version, which is not yet out on Pip. You can either install Opacus from source or wait for the next release (1.0 should be out in a week or so).
