### ISSUE TITLE
Couldn't import DPGRU

### ISSUE THREAD

**Issue by anik123** [pytorch/opacus#275]
I have tried to use gru in opacus as shown in the documentation https://opacus.ai/api/dp_rnn.html. However, I tried to import it in google colab in the following way,

![image](https://user-images.githubusercontent.com/6007117/143210369-a74c4c94-2030-4551-807a-1d73d94d823e.png)

It gave me the following error: 

![image](https://user-images.githubusercontent.com/6007117/143210492-26e13ba0-83ce-4cc6-93dd-1bee4c8d8562.png)

Any help? Thanks in advance.

**Comment by alexandresablayrolles** [comment]
Thanks for flagging this issue. I believe that the latest Pip release (0.14, from June) does not have the DPGRU as it is a very recent commit. You can either install Opacus from source (see README) or wait for the next release (1.0 should be out in a week)

**Comment by karthikprasad** [comment]
FYI, Opacus 0.15.0 has been released with support fort DPGRU.

**Comment by anik123** [comment]
Thanks for your support. It's working.
