### ISSUE TITLE
Specify Opacus Version number on Tutorials

### ISSUE THREAD

**Issue by RoyRin** [pytorch/opacus#292]
## 📚 Documentation (tutorials)

Tutorials like https://opacus.ai/tutorials/building_image_classifier have changed in the last few days, but don't link to the opacus version that they are using. If something like a  requirements.txt or pyproject.toml could be included (or even something as simple as a comment about the opacus version), this would be helpful.

For example:

`from opacus.validators import ModuleValidator` in the image classifier produces the error `ModuleNotFoundError: No module named 'opacus.validators'` on opacus 0.15.0 and I do not know what version of opacus has `opacus.validators`

**Comment by ffuuugor** [comment]
Hi!
Thanks for flagging - that's definitely valid concern. We'll think about how to best indicate this.

The latests tutorials indeed doesn't work with `opacus==0.15`. As a temporary workaround you can either build opacus from source (latest main) or wait until the opacus in updated on PyPI (coming very soon!)

**Comment by RoyRin** [comment]
Is there a public roadmap for Opacus development that we can refer to, in order make longer-term decisions about what software to use?

**Comment by ffuuugor** [comment]
Unfortunately not at the moment. We use github issues to track feature requests (or bug reports) from the community, and we're doing our best to be responsive to those requests - supporting community is important for use.

We, however, don't, as of now, have a good way of communicating the relative priorities of those issues.

It's also worth noting, that starting from v1.0.0 (released today) we don't plan to introduce any breaking changes without gracious deprecation period.
