### ISSUE TITLE
[BUG] Hidden states of RNN is not passed into device.

### ISSUE THREAD

**Issue by birdx0810** [pytorch/opacus#311]
## 🐛 Bug

`hs` and `cs` are not passed in to the device, however the `unsorted_indices` are passed into device. Therefore, there would be a `RuntimeError` raised regarding discrepancy of devices when the `apply_permutation` function is called if the model was passed into a GPU device.

https://github.com/pytorch/opacus/blob/5cd23cf8040b15460ebf317b2f3ef0cee9e39ad6/opacus/layers/dp_rnn.py#L431-L435

## To Reproduce

This error could be reproduced through this [Colab](https://colab.research.google.com/drive/1RysLoStXqxaft4TbyFxGj_kx-Sa355ir?usp=sharing). Hardware accelerator should be set to GPU, using CPU would not raise this issue.

## Expected behavior

The following error would be raised in the last cell of the Colab example.
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

## Environment

PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A
OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2070 SUPER
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.8.1
[pip3] torch-optimizer==0.1.0
[pip3] torch-tb-profiler==0.1.0
[pip3] torchcsprng==0.2.1
[pip3] torchgan==0.0.5
[pip3] torchvision==0.9.1
[conda] Could not collect

## Additional context

This issue could be resolved by adding `.to(device)` to L431 and L434. However, I'm not sure if this is the best way to resolve this.

**Comment by alexandresablayrolles** [comment]
Thanks for reaching out! We're looking into this and will update the issue when we've fixed the problem.
