### ISSUE TITLE
Getting "ValueError: Unexpected grad_sample type: <class 'NoneType'>" for self-supervised training.

### ISSUE THREAD

**Issue by vangorade** [pytorch/opacus#312]
Congratulations on the new opacus version release!

I am trying to train a contrastive learning model on time-series data with opacus version 1.0 by following the official [tutorial ](https://github.com/pytorch/opacus/blob/main/tutorials/building_image_classifier.ipynb).

Error:
"ValueError: Unexpected grad_sample type: <class 'NoneType'>"

Full error:
    model_optimizer.step()  -> error starts from this line in my code.
  File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 478, in step
    if self.pre_step():
  File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 459, in pre_step
    self.clip_and_accumulate()
  File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 366, in clip_and_accumulate      
    g.view(len(g), -1).norm(2, dim=-1) for g in self.grad_samples
  File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 313, in grad_samples
    ret.append(_get_flat_grad_sample(p))
  File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 186, in _get_flat_grad_sample    
    raise ValueError(f"Unexpected grad_sample type: {type(p.grad_sample)}")
ValueError: Unexpected grad_sample type: <class 'NoneType'>

Thank you.

**Comment by weiiewwei** [comment]
I have met the same error and don't konw how to solve it.
The error happened in the code:  optimizer.step(), when training the model.

Traceback (most recent call last):
  File "train_model_DPSGD_wyq.py", line 439, in <module>
    main(args)
  File "train_model_DPSGD_wyq.py", line 331, in main
    optimizer.step()
  File "/usr/local/lib/python3.7/dist-packages/opacus/optimizers/optimizer.py", line 478, in step
    if self.pre_step():
  File "/usr/local/lib/python3.7/dist-packages/opacus/optimizers/optimizer.py", line 459, in pre_step
    self.clip_and_accumulate()
  File "/usr/local/lib/python3.7/dist-packages/opacus/optimizers/optimizer.py", line 366, in clip_and_accumulate
    g.view(len(g), -1).norm(2, dim=-1) for g in self.grad_samples
  File "/usr/local/lib/python3.7/dist-packages/opacus/optimizers/optimizer.py", line 313, in grad_samples
    ret.append(_get_flat_grad_sample(p))
  File "/usr/local/lib/python3.7/dist-packages/opacus/optimizers/optimizer.py", line 186, in _get_flat_grad_sample
    raise ValueError(f"Unexpected grad_sample type: {type(p.grad_sample)}")
ValueError: Unexpected grad_sample type: <class 'NoneType'>

**Comment by weiiewwei** [comment]
> Congratulations on the new opacus version release!
> 
> I am trying to train a contrastive learning model on time-series data with opacus version 1.0 by following the official [tutorial ](https://github.com/pytorch/opacus/blob/main/tutorials/building_image_classifier.ipynb).
> 
> Error: "ValueError: Unexpected grad_sample type: <class 'NoneType'>"
> 
> Full error: model_optimizer.step() -> error starts from this line in my code. File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 478, in step if self.pre_step(): File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 459, in pre_step self.clip_and_accumulate() File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 366, in clip_and_accumulate g.view(len(g), -1).norm(2, dim=-1) for g in self.grad_samples File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 313, in grad_samples ret.append(_get_flat_grad_sample(p)) File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 186, in _get_flat_grad_sample raise ValueError(f"Unexpected grad_sample type: {type(p.grad_sample)}") ValueError: Unexpected grad_sample type: <class 'NoneType'>
> 
> Thank you.



> Congratulations on the new opacus version release!
> 
> I am trying to train a contrastive learning model on time-series data with opacus version 1.0 by following the official [tutorial ](https://github.com/pytorch/opacus/blob/main/tutorials/building_image_classifier.ipynb).
> 
> Error: "ValueError: Unexpected grad_sample type: <class 'NoneType'>"
> 
> Full error: model_optimizer.step() -> error starts from this line in my code. File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 478, in step if self.pre_step(): File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 459, in pre_step self.clip_and_accumulate() File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 366, in clip_and_accumulate g.view(len(g), -1).norm(2, dim=-1) for g in self.grad_samples File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 313, in grad_samples ret.append(_get_flat_grad_sample(p)) File "/mnt/f/AI_research/TS-TCC-main/opacus/opacus/optimizers/optimizer.py", line 186, in _get_flat_grad_sample raise ValueError(f"Unexpected grad_sample type: {type(p.grad_sample)}") ValueError: Unexpected grad_sample type: <class 'NoneType'>
> 
> Thank you.

Have you solved this error?

**Comment by vangorade** [comment]
I can't able to solve it yet.

**Comment by weiiewwei** [comment]
> 

so sad, :(

**Comment by ashkan-software** [comment]
Another user of Opacus has seen a similar issue: https://discuss.pytorch.org/t/valueerror-unexpected-grad-sample-type-class-nonetype-when-trying-to-train-with-differential-privacy/140339

Would any of you be able to provide us with the code so we can debug?

**Comment by kpandl** [comment]
Hello together,
I am the other user from the PyTorch forum. Here is a simplified code that produces the error.

`import torch
from torchvision import  models
from torch import nn
import numpy as np
import torchvision.transforms as transforms
from torchvision.datasets import CIFAR10
import torch.nn.functional as F
from opacus import PrivacyEngine
from opacus.validators import ModuleValidator

model = models.densenet121(pretrained=True)
num_ftrs_model = model.classifier.in_features
model.classifier = nn.Sequential(nn.Linear(num_ftrs_model, 10), nn.Sigmoid())
model_state_dict = model.state_dict()

dataset = CIFAR10(root='data/', download=True, transform=transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset,batch_size=16, shuffle=True, num_workers=4, pin_memory=True)
optimizer = torch.optim.Adam(params=filter(lambda p: p.requires_grad, model.parameters()), lr=0.01)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
criterion = nn.BCELoss().to(device)

running_loss = 0.0

use_differential_privacy = True

if __name__ == "__main__":

    privacy_engine = PrivacyEngine()
    
    if(use_differential_privacy):
        model = ModuleValidator.fix(model)
        model, optimizer, train_loader = privacy_engine.make_private(
        module=model,
        optimizer=optimizer,
        data_loader=train_loader,
        noise_multiplier=1.1,
        max_grad_norm=1.0)
    
    model = model.to(device)

    for i, data in enumerate(train_loader):
        imgs, labels_sing = data

        labels = F.one_hot(labels_sing, num_classes=10)
        labels = labels.to(torch.float32)

        batch_size = imgs.shape[0]
        imgs = imgs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        model.train()
        outputs = model(imgs)

        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss * batch_size

    epoch_loss_train = running_loss / len(dataset)

    if(use_differential_privacy):
        epsilon, best_alpha = privacy_engine.accountant.get_privacy_spent(
            delta=1/(10*len(dataset))
        )
        print(
            f"Train Epoch: ka \t"
            f"Loss: {np.mean(epoch_loss_train):.6f} "
            f"(ε = {epsilon:.2f}, δ = {1/(10*len(dataset))}) for α = {best_alpha}"
        )`

The PyTorch version is 1.10.0+cu102, the Opacus version is 1.0.0. Would be great if you can look into it. Thanks!

**Comment by romovpa** [comment]
@kpandl Thanks for providing the code! The problem with your example is initializing the optimizer before running `ModuleValidator.fix(model)` which changes the parameters.

The sequence of actions is the following:
```
model = models.densenet121(pretrained=True)
optimizer = torch.optim.Adam(params=filter(..., model.parameters()), lr=0.01)
model = ModuleValidator.fix(model)
model, optimizer, train_loader = privacy_engine.make_private(...)
```
`ModuleValidator.fix` changes the model by replacing submodules after which some of the parameters you passed to `Adam(params=...)` no longer used in the model. The previously created optimizer cannot be used with the new model. `make_private` doesn't prepare old parameters for collecting grad_samples, that's why we get `Unexpected grad sample type`.

To fix this, re-create the optimizer after applying ModuleValidator.fix:

```
    if(use_differential_privacy):
        model = ModuleValidator.fix(model)
        optimizer = torch.optim.Adam(params=filter(lambda p: p.requires_grad, model.parameters()), lr=0.01)
        model, optimizer, train_loader = privacy_engine.make_private(...)
```

**Comment by romovpa** [comment]
@vangorade @weiiewwei 
Try to make sure the optimizer uses parameters from the model you apply `make_private()` to. Note that `ModuleValidator.fix` changes the set of parameters. See [my previous comment](https://github.com/pytorch/opacus/issues/312#issuecomment-1016953478), you may have the same problem. If your problem is different, please provide us with the code to reproduce it and reopen this issue.

I've added a PR #331 to make the exception message slightly more informative.
