### ISSUE TITLE
Poisson sampling support

### ISSUE THREAD

**Issue by YukeWang96** [pytorch/opacus#320]
When I try AlexNet with opacus, I got the error like
```
ValueError: Poisson sampling is not compatible with grad accumulation. You need to call optimizer.step() after every forward/backward pass or consider using BatchMemoryManager
```
is there any solution or workaround?

**Comment by karthikprasad** [comment]
Hello! Could you share your code in a colab to aid debugging? Please feel free to compare your code against the tutorial at https://opacus.ai/tutorials/building_image_classifier for sanity check.
