### ISSUE TITLE
DPOptimizer should pass through defaults

### ISSUE THREAD

**Issue by gkaissis** [pytorch/opacus#322]
DPOptimizer doesn't pass through the .defaults attribute of the original optimizer. Since this can include things like momentum, this can break code using schedulers. For example, when using NAdam, schedulers with cycle_momentum=True will not fail as intended because NAdam has no momentum, but will instead fail on the attribute lookup for the .defaults attribute on the wrapped optimizer.
Proposed fix:

self.defaults = self.original_optimizer.defaults

**Comment by alexandresablayrolles** [comment]
Thanks for flagging, we have a PR to fix it (https://github.com/pytorch/opacus/pull/329)

**Comment by alexandresablayrolles** [comment]
Closing this issue as PR was merged.
