### ISSUE TITLE
`DistributedPerLayerOptimizer` does not work on v1.0.1

### ISSUE THREAD

**Issue by ndrmnl** [pytorch/opacus#324]
## 🐛 Bug

The `DistributedPerLayerOptimizer` inside `optimizers/ddp_perlayeroptimizer.py` raises errors when used. In particular:

1. L20 always fails since `p.summed_grad` is initialized as `None`
2. The `pre_step` always fails on L84 because `self.accumulated_iterations` is a property defined in `DPOptimizer`. Also, it does not `return True`, so nothing happens on `DPOptimizer.step`.

There might be more issues, I only investigated briefly.

## To Reproduce

Just create a `DistributedPerLayerOptimizer` using standard arguments.

## Expected behavior

I thought this would work just as the DDP hooks present in Opacus 0.15. Apologies if it's indeed not supposed to work/being deprecated/etc., but I couldn't find this info anywhere. Moreover, I noticed the `get_optimizer_class` function will indeed return this class when `clipping == per_layer` and `distributed is True`.

**Comment by ndrmnl** [comment]
Btw I've tried fixing the two points above, it then runs but doesn't give the same result as DPDDP w/ zero noise and large max_grad_norm (in Opacus 0.15 it would). So there's something else going on.

**Comment by alexandresablayrolles** [comment]
Thanks for flagging @ndrmnl, we are looking into it.

**Comment by alexandresablayrolles** [comment]
We have a fix (#347)

**Comment by ffuuugor** [comment]
#347 is landed, closing the issue
