### ISSUE TITLE
About running

### ISSUE THREAD

**Issue by chensquan** [pytorch/opacus#332]
Dear Author,
   When I run the mnist.py ,it exists something wrong like this:

![ZLN{P%W)}QP_$%CW8INQG6M](https://user-images.githubusercontent.com/52994399/150325300-79e08584-e9a0-4739-ae5f-999131f2ff1d.png)
   why the opacus can't be recognized?

**Comment by alexandresablayrolles** [comment]
It seems from the error message that you haven't installed opacus?
