### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'module'

### ISSUE THREAD

**Issue by jeff19960430** [pytorch/opacus#336]
privacy_engine = PrivacyEngine()
centralized_model,centralized_optimizer,train_dl=privacy_engine.make_private(
                                                        module=centralized_model,
                                                        optimizer=centralized_optimizer,
                                                        data_loader=train_dl,
                                                        noise_multiplier=1.3,   
                                                        max_grad_norm=1.0) 

when I run this code,report the error abrove: 
TypeError: __init__() missing 1 required positional argument: 'module'

**Comment by jeff19960430** [comment]
![image](https://user-images.githubusercontent.com/42458424/151662623-72c6695d-c3e2-4a92-91b9-dcc3446b4f15.png)

**Comment by karthikprasad** [comment]
Hi! You are most likely using the older version of Opacus. You can follow the migration guide at https://github.com/pytorch/opacus/blob/main/Migration_Guide.md to make your code compatible with Opacus 1.0.

Please feel free to reopen the issue if this doesn't solve your issue.

**Comment by jeff19960430** [comment]
so , how I change the Opacus to 1.0 . I just follow the guide

**Comment by jeff19960430** [comment]
# define your components as usual
model = Net()
optimizer = SGD(model.parameters(), lr=0.05)
data_loader = torch.utils.data.DataLoader(dataset, batch_size=1024)

# enter PrivacyEngine
privacy_engine = PrivacyEngine()
model, optimizer, data_loader = privacy_engine.make_private(
    module=model,
    optimizer=optimizer,
    data_loader=data_loader,
    noise_multiplier=1.1,
    max_grad_norm=1.0,
)
# Now it's business as usual

I follow this code

**Comment by jeff19960430** [comment]
I mean i fully follow the textbook
and this : privacy_engine = PrivacyEngine()
report error

**Comment by karthikprasad** [comment]
> so , how I change the Opacus to 1.0

Could you verify if the following snippet prints 1.0, 1.0.1?
```
import opacus
print(opacus.__version__)
```

If yes, please share a colab so that we can debug this further.
If not, you'll have to upgrade opacus with `pip install --upgrade opacus`

**Comment by jeff19960430** [comment]
i print the version of the opacus,it;s 0.14. So I upgrade it ,and I find the highest vision is 0.15

![image](https://user-images.githubusercontent.com/42458424/151902907-5f423b10-3dc7-4551-8a68-067b33c80f69.png)

**Comment by jeff19960430** [comment]
![image](https://user-images.githubusercontent.com/42458424/151903051-11b37ed1-a5d6-435d-8f90-ad066a08f78e.png)

**Comment by karthikprasad** [comment]
A couple of comments:
1. The correct command is `pip install opacus==1.0.1` (notice the absence of the letter `v`)
2. Looking at the listed available versions, my guess is you are using Python 3.6. Opacus 1.0 is supported on Python 3.7.5 and above.

If neither of the above works, please share a colab to aid debugging. It is genuinely hard to debug with mere screenshots.

**Comment by jeff19960430** [comment]
So,I need to upgrade Python first?

**Comment by jeff19960430** [comment]
my Python is 3.7

**Comment by jeff19960430** [comment]
thank you ! and I want to consult you about how wo  adjusting the noise increase parameter for each round.
The current noise increase parameter is bound to the optimizer, which means that each gradient descent can only use the same coefficient, and if I want to automatically change the noise coefficient, how can I make the gradient descent, and how to get the current privacy budget

**Comment by karthikprasad** [comment]
> and I want to consult you about how wo adjusting the noise increase parameter for each round.

Hi! Absolutely! Although, this question is unrelated to the main topic of the issue. It is being actively discussed on the forum at https://discuss.pytorch.org/t/how-to-adjusting-the-noise-increase-parameter-for-each-round/143548, so let's continue it there.
Thanks.

**Comment by jeff19960430** [comment]
OK thank you
