### ISSUE TITLE
Huggingface's generate() usage

### ISSUE THREAD

**Issue by SeolhwaLee** [pytorch/opacus#341]
## ❓ Questions and Help

Hi, I'm implementing my code based on BART from huggingface with Opacus.

I tried to apply to generate() to see the model generate results at every end of epochs. 

But, the error occurs like ``AttributeError: 'GradSampleModule' object has no attribute 'generate'``

The original code for using ``model.generate()`` works well since this function is derived from huggingface's BART code.

But it seems got the error due to using ``model, .. = privacy_engine.make_private_with_epsilon``

Could you give any tips for resolving this?

Thanks in advance.

### Before asking:
1. Search the [FAQs](https://opacus.ai/docs/faq).
2. Search our [Forums](https://discuss.pytorch.org/search?q=question%20category%3A29).
3. Search the [Docs](https://opacus.ai/api/).

> :warning: **This issue tracker is not a help form and this issue will be closed**.

Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/c/opacus/29). We actively monitor questions you post in the PyTorch forums with the category `Opacus`.

**Comment by ffuuugor** [comment]
Hi!
One thing you can try is accessing the underlying model with `model._module.generate()`:
Model returned from `make_private_with_epsilon` is a wrapper around the model you've provided as an input, but we only wrap certain attributed. By accessing `model._module` you get full access to the original model object.

Hope this helps, and if not - it'd be very helpful if you could share the code so we can investigate further.
I'll close down the issue for now, feel free to either reopen it or post to PyTorch forums in opacus category: https://discuss.pytorch.org/c/opacus/29

**Comment by SeolhwaLee** [comment]
@ffuuugor Thank you! It works well :)
