### ISSUE TITLE
About DPGAN

### ISSUE THREAD

**Issue by chensquan** [pytorch/opacus#361]
Dear author, when I use opacus  to  GAN , the effects is so poor ，adapts  the parameters sigma，c,  the generator image is so poor.until the sigma=0.01, the effects is getting better，but the epslion is too large to realize the protection。would you mind telling me the problem?

**Comment by chensquan** [comment]
Besides,when I want to use gpu to run the code，how to input the parameter device  ? hope to hearing from you

**Comment by karthikprasad** [comment]
> but the epslion is too large to realize the protection。would you mind telling me the problem?

Hi @chensquan, it is impossible to help identify the problem without a code notebook to look at. The best we can say in the absence of context is that DP adds noise and is known to hurt performance.
Have you tried the dcgan MNIST example under the opacus examples folder? What parameters worked for you? What is your target epsilon?

> Besides,when I want to use gpu to run the code，how to input the parameter device ? hope to hearing from you

If your code is using similar args as that of dcgan.py under examples, you can set `--device cuda:0` to use GPU.

**Comment by karthikprasad** [comment]
Also just a reminder on the logistical side: you can always ask opacus related questions and ask for support on PyTorch forums: https://discuss.pytorch.org/c/opacus/29
This opens up the question to broader community and will also keep the questions in one place, leaving Github issues code related bugs and features.

I'll close this issue for now. Please feel free to post on the forum if you have any follow-up questions.

**Comment by chensquan** [comment]
My target epsilon is <=10, However， the generator image is so poor. When the sigma=0.01,&nbsp; the generator image can see clear, but the epsilon is up to 400000000+, I don't know the problem。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pytorch/opacus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 凌晨4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pytorch/opacus] About DPGAN (Issue #361)





  
but the epslion is too large to realize the protection。would you mind telling me the problem?
  
Hi @chensquan, it is impossible to help identify the problem without a code notebook to look at. The best we can say in the absence of context is that DP adds noise and is known to hurt performance.
 Have you tried the dcgan MNIST example under the opacus examples folder? What parameters worked for you? What is your target epsilon?
  
Besides,when I want to use gpu to run the code，how to input the parameter device ? hope to hearing from you
  
If your code is using similar args as that of dcgan.py under examples, you can set --device cuda:0 to use GPU.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chensquan** [comment]
when I run the dcgan.py example，I set the batch_size=32, my gpu type is 1080Ti，it runs 8 epochs ,then call CUDA out of memory, how can I solve this problem？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pytorch/opacus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 凌晨4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pytorch/opacus] About DPGAN (Issue #361)





  
but the epslion is too large to realize the protection。would you mind telling me the problem?
  
Hi @chensquan, it is impossible to help identify the problem without a code notebook to look at. The best we can say in the absence of context is that DP adds noise and is known to hurt performance.
 Have you tried the dcgan MNIST example under the opacus examples folder? What parameters worked for you? What is your target epsilon?
  
Besides,when I want to use gpu to run the code，how to input the parameter device ? hope to hearing from you
  
If your code is using similar args as that of dcgan.py under examples, you can set --device cuda:0 to use GPU.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by karthikprasad** [comment]
Interesting. Could you post this question on the opacus forum at https://discuss.pytorch.org/c/opacus/29 with a colab?
