### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 10035200 bytes.

### ISSUE THREAD

**Issue by jeff19960430** [pytorch/opacus#389]
## 🐛 Bug

 privacy_engine = PrivacyEngine()
    model, optimizer, data_loader = privacy_engine.make_private(
        module=centralized_model,
        optimizer=centralized_optimizer,
        data_loader=train_dl,
        noise_multiplier=1.1,
        max_grad_norm=1.0,
    )

when I use the code , it will cause the error just like the title 。and when I remove the code, it will ok . the batch_size=16

![image](https://user-images.githubusercontent.com/42458424/159123655-6415f156-8f61-4087-9c0c-535a22c443d1.png)

**Comment by jeff19960430** [comment]
may be there are some relation about this ?

**Comment by alexandresablayrolles** [comment]
Thanks for reporting this issue. It looks like you were not able to allocate 10MB of RAM? How much RAM do you have in total? Is another process taking up your RAM?

**Comment by jeff19960430** [comment]
I have 16GB RAM in total . there are not other process in my RAM

**Comment by jeff19960430** [comment]
so,what the problem about this? If I remove this code , I can train my model normal

**Comment by alexandresablayrolles** [comment]
Can you share the code, or a minimum reproducing example? I have another idea why there may be a problem: the PrivacyEngine is returning "model" but you seem to be using "centralized_model" in the rest of the code (I'm guessing that  because "model" is greyed out). You should modify your code to be:
```
centralized_model, centralized_optimizer, train_dl = privacy_engine.make_private(...)
```
