### ISSUE TITLE
ValueError: Per sample gradient is not initialized. Not updated in backward pass?

### ISSUE THREAD

**Issue by Nanboy-Ronan** [pytorch/opacus#414]
## 🐛 Bug

I am continuously getting "ValueError: Per sample gradient is not initialized. Not updated in backward pass?" Is there any idea?

## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1.
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by nBoeninger** [comment]
Got the same error msg as well, not sure what lead to it for now...

**Comment by pierrestock** [comment]
Hey [Nanboy-Ronan](https://github.com/Nanboy-Ronan) and [nBoeninger](https://github.com/nBoeninger), 

Thanks for your interest in Opacus! Could you provide us more details (code snippets) to reproduce this behaviour? Most likely, the backward pass did not happen or did not apply to the particular module that complains.

Thanks,
Pierre

**Comment by nBoeninger** [comment]
Hi,
so in my case it was due to an misplaced zero_grad() call. Looking at the provided exampels solved this issue at least for me 

Thanks,
Nico

**Comment by Flyige** [comment]
Hi,
i'm using opacus in seqGAN and also facing this problem,is there anyway to fix this bug?
