### ISSUE TITLE
ValueError: Per sample gradient is not initialized. Not updated in backward pass?

### ISSUE THREAD

**Issue by kpandl** [pytorch/opacus#431]
## 🐛 Bug

Hello,

I am trying to run an image classification densenet on the CIFAR-10 using opacus, but I get the "ValueError: Per sample gradient is not initialized. Not updated in backward pass?" error. This bug has been discussed [before](https://github.com/pytorch/opacus/issues/414), but not really in a reproducible manner - here, I provide code, hoping others can reproduce it and help fixing it.

My code is as follows:

    import torch
    from torchvision import  models
    from torch import nn
    import numpy as np
    import torchvision.transforms as transforms
    from torchvision.datasets import CIFAR10
    import torch.nn.functional as F
    from opacus import PrivacyEngine
    from opacus.validators import ModuleValidator

    dataset = CIFAR10(root='data/', download=True, transform=transforms.ToTensor())
    train_loader = torch.utils.data.DataLoader(dataset,batch_size=8, shuffle=True, num_workers=20, pin_memory=True)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    criterion = nn.BCELoss().to(device)

    running_loss = 0.0

    use_differential_privacy = True

    if __name__ == "__main__":

        model = models.densenet121(pretrained=True)
        num_ftrs = model.classifier.in_features
        model.classifier = nn.Sequential(nn.Linear(num_ftrs, 10), nn.Sigmoid())
        optimizer = torch.optim.SGD(model.parameters(),lr=0.01,momentum=0,weight_decay=0)

        if(use_differential_privacy):
            print("use differentialprivacy")
            model = ModuleValidator.fix(model)
            privacy_engine = PrivacyEngine()
            model, optimizer, train_loader = privacy_engine.make_private(
            module=model,
            optimizer=optimizer,
            data_loader=train_loader,
            noise_multiplier=1.1,
            max_grad_norm=1.0)

        model = model.to(device)
        
        print_freq = 1000
        running_loss = 0.0

        for i, data in enumerate(train_loader):
        imgs, labels = data

        batch_size = imgs.shape[0]
        imgs = imgs.to(device)
        labels = labels.to(device)

        
        labels = F.one_hot(labels, num_classes=10)
        labels = labels.to(torch.float32)

        optimizer.zero_grad()
        model.train()
        outputs = model(imgs)

        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()  # update weights

        running_loss += loss * batch_size
        if (i % print_freq == 0):
            print(str(i * batch_size))

        epoch_loss_train = running_loss / len(dataset)

        if(use_differential_privacy):
            epsilon, best_alpha = privacy_engine.accountant.get_privacy_spent(
                delta=1/(10*len(dataset))
            )
            print("finished local training, privacy report:", privacy_engine.accountant.get_privacy_spent(delta=1/(10*len(train_loader))))

        print("finished")

The above code produces the error when going over the optimizer.step() call. When I set use_differential_privacy=False and deactivate the Opacus parts of the code, it runs fine. My PyTorch version is 1.10.2+cu113, my Opacus version is 1.1.2, my Python version is 3.7.11.

Can you please help me in fixing the bug? What mistake am I making? Thanks!

**Comment by tdye24** [comment]
same problem as you and i have no idea yet

**Comment by karthikprasad** [comment]
Hi @kpandl, thanks for raising the issue.

Your code is failing because `model = ModuleValidator.fix(model)` is called after passing `model.parameters()` to optimizer. 
`ModuleValidator.fix(model)` changes some layers of the model (specifically replaces `BatchNorm` with `GroupNorm`) and the parameters of these new layers are not tracked by optimizer.

Calling `fix()` before defining optimizer should work.

That said, your issue does create two action items for us:
1. At the very least, print a warning/throw an error when params in optimizer are not the same as that of modules.
2. Print a more helpful message in case of failures. (not sure how)

**Comment by karthikprasad** [comment]
I'll close this issue for now and will track the action items in the newly created issue linked above. Please feel free to reopen if this doesn't solve your problem.

**Comment by Hafizamariaiqbal** [comment]
'PRVAccountant' object has no attribute 'get_privacy_spent'
