### ISSUE TITLE
Using Opacus with Neural Additive Models 

### ISSUE THREAD

**Issue by albertyusun** [pytorch/opacus#454]
## 🐛 Bug

I'm attempting to add differential privacy to [Neural Additive Models (NAMs)](https://arxiv.org/pdf/2004.13912.pdf
) as implemented [here](https://github.com/facebookresearch/nbm-spam/blob/main/nbm_spam/models/concept_nam.py) for interpretable machine learning by Filip Radenovic et al. 

The model, as implemented in Filip's code base ([ConceptNAMNary](https://github.com/facebookresearch/nbm-spam/blob/main/nbm_spam/models/concept_nam.py)), essentially implements a neural net with sequential layers comprised of an arbitrary combination of Conv1d layers, BatchNorm layers, and ReLU activation functions. I used `nam = ModuleValidator.fix(nam)` to fix initial errors about changing Batch Norm to Group Norm. 

When I fit a NAM after using the privacy engine, I receive an error where Opacus doesn't support ConceptNAMNary.  ConceptNAMNary inherits from nn.Module and implements ConceptNNNary, another inheritor of nn.Module. Both ConceptNAMNary and ConceptNNary can be found in the same [file](https://github.com/facebookresearch/nbm-spam/blob/main/nbm_spam/models/concept_nam.py). 

How do I fix the following error? My suspicion is that I have to use Opacus to recognize the layers of the sequential model within the broader wrapper of the model. Do I have to register the ConceptNAMNary "wrapper"? Do I have to 'peel back' ConceptNAMNary and add the privacy engine to a primitive NN with only the Conv1d, GroupNorm, ReLU layers? Any tips on this would be extremely helpful!

## To Reproduce

1. Here is a [Colab Link](https://colab.research.google.com/drive/10bHdIUS6QDwT00Ge54-sIQYbA6Hv-3MR?usp=sharing) to reproduce a simple example. 

2. Initialize a [ConceptNAMNary](https://github.com/facebookresearch/nbm-spam/blob/main/nbm_spam/models/concept_nam.py).

3. Attempt to fit a ConceptNAMNary using the Opacus privacy engine.

```
UnsupportedModuleError: 

[NotImplementedError("Model contains a trainable layer that Opacus doesn't currently support(:

ConceptNAMNary(
(concept_dropout): Dropout(p=0.0, inplace=False)
  (concept_nary_nns): ModuleDict(
    (ord1_net0): ConceptNNNary(
      (model): Sequential(
        (0): Conv1d(8, 512, kernel_size=(1,), stride=(1,), groups=8)
        (1): GroupNorm(32, 512, eps=1e-05, affine=True)
        (2): ReLU()
        (3): Conv1d(512, 512, kernel_size=(1,), stride=(1,), groups=8)
        (4): GroupNorm(32, 512, eps=1e-05, affine=True)
        (5): ReLU()
        (6): Conv1d(512, 256, kernel_size=(1,), stride=(1,), groups=8)
        (7): GroupNorm(32, 256, eps=1e-05, affine=True)
        (8): ReLU()
        (9): Conv1d(256, 8, kernel_size=(1,), stride=(1,), groups=8)
      )
    )
  )
)). 

Please implement and register grad sampler for this layer. (See opacus.grad_sample.utils.register_grad_sampler)")]
```

## Expected behavior

I expect my NAM model to be differentially private (work well with the Opacus privacy engine) and run without bugs. 

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.2
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): Used Jupyter notebook
 - Python version: 3.8.13
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A Didn't use any GPUs
 - Any other relevant information:

**Comment by romovpa** [comment]
Thanks @albertyusun for the detailed explanation and the code!

This bug is actually a limitation of our gradient sampler: it can only handle modules for which either a custom grad sampler is implemented or if it is a "wrapper" containing other submodules (and not parameters).

`ConceptNAMNary` is not a pure "wrapper module": it contains both submodules and custom weights. Without custom parameters (`module._bias` and `module._weight` in your case) we could deal with it. 

There is an easy way to make this work, but it requires changing the code of `ConceptNAMNary` a little bit. If you wrap the hanging parameters `_bias, _weight` into nn.Linear and add it as a trainable submodule, it must work.

**Comment by romovpa** [comment]
I wonder if ExpandedWeights can handle this automatically @ffuuugor

**Comment by ffuuugor** [comment]
It could - looking at the code, `_weight` and `_bias` are only used in `F.linear` calls, which indicates that `ExpandedWeight` should be able to handle it.
Please note that ExpandedWeight integration is still in beta and we don't have a tutorial on it, but you can take a look at #441  for some context and examples

**Comment by albertyusun** [comment]
Gotcha, thanks @romovpa and @ffuuugor for the directions! For now, I'll just try wrapping the linear layer, that makes sense.

I just tried using expanded weights (`grad_sample_mode='ew'`), and it's unfortunately raising the same `UnsupportedModuleError `error. Using the same model, optimizer, and train_loader as shown in the above colab file, here's the code and the following error I'm receiving: 

### Code:

```
nam = ModuleValidator.fix(nam)

privacy_engine = PrivacyEngine()
input_model, input_optimizer, input_train_loader = privacy_engine.make_private_with_epsilon(
    module=nam,
    optimizer=optimizer,
    data_loader=train_loader,
    target_epsilon=1,
    target_delta=1e-6,
    epochs=1000,
    max_grad_norm=1.0,
    grad_sample_mode="ew"
)
```

### Error:
```
---------------------------------------------------------------------------
UnsupportedModuleError                    Traceback (most recent call last)
Input In [11], in <cell line: 4>()
      1 nam = ModuleValidator.fix(nam)
      3 privacy_engine = PrivacyEngine()
----> 4 input_model, input_optimizer, input_train_loader = privacy_engine.make_private_with_epsilon(
      5     module=nam,
      6     optimizer=optimizer,
      7     data_loader=train_loader,
      8     target_epsilon=1,
      9     target_delta=1e-6,
     10     epochs=1000,
     11     max_grad_norm=1.0,
     12     grad_sample_mode="ew"
     13 )

File ~\Miniconda3\envs\interpretml\lib\site-packages\opacus\privacy_engine.py:528, in PrivacyEngine.make_private_with_epsilon(self, module, optimizer, data_loader, target_epsilon, target_delta, epochs, max_grad_norm, batch_first, loss_reduction, noise_generator, grad_sample_mode, **kwargs)
    521 if len(self.accountant) > 0:
    522     warnings.warn(
    523         "You're calling make_private_with_epsilon with non-zero privacy budget "
    524         "already spent. Returned noise_multiplier assumes zero starting point, "
    525         "so your overall privacy budget will be higher."
    526     )
--> 528 return self.make_private(
    529     module=module,
    530     optimizer=optimizer,
    531     data_loader=data_loader,
    532     noise_multiplier=get_noise_multiplier(
    533         target_epsilon=target_epsilon,
    534         target_delta=target_delta,
    535         sample_rate=sample_rate,
    536         epochs=epochs,
    537         accountant=self.accountant.mechanism(),
    538         **kwargs,
    539     ),
    540     max_grad_norm=max_grad_norm,
    541     batch_first=batch_first,
    542     loss_reduction=loss_reduction,
    543     noise_generator=noise_generator,
    544     grad_sample_mode=grad_sample_mode,
    545 )

File ~\Miniconda3\envs\interpretml\lib\site-packages\opacus\privacy_engine.py:418, in PrivacyEngine.make_private(self, module, optimizer, data_loader, noise_multiplier, max_grad_norm, batch_first, loss_reduction, poisson_sampling, clipping, noise_generator, grad_sample_mode)
    412     raise ValueError(
    413         "Module parameters are different than optimizer Parameters"
    414     )
    416 distributed = isinstance(module, (DPDDP, DDP))
--> 418 module = self._prepare_model(
    419     module,
    420     batch_first=batch_first,
    421     loss_reduction=loss_reduction,
    422     grad_sample_mode=grad_sample_mode,
    423 )
    424 if poisson_sampling:
    425     module.register_backward_hook(forbid_accumulation_hook)

File ~\Miniconda3\envs\interpretml\lib\site-packages\opacus\privacy_engine.py:238, in PrivacyEngine._prepare_model(self, module, batch_first, loss_reduction, grad_sample_mode)
    228 def _prepare_model(
    229     self,
    230     module: nn.Module,
   (...)
    236     # Ideally, validation should have been taken care of by calling
    237     # `get_compatible_module()`
--> 238     self.validate(module=module, optimizer=None, data_loader=None)
    240     # wrap
    241     if isinstance(module, AbstractGradSampleModule):

File ~\Miniconda3\envs\interpretml\lib\site-packages\opacus\privacy_engine.py:303, in PrivacyEngine.validate(self, module, optimizer, data_loader)
    283 def validate(
    284     self,
    285     *,
   (...)
    288     data_loader: Optional[DataLoader],
    289 ):
    290     """
    291     Validate that task components are compatible with DP.
    292     Same as ``is_compatible()``, but raises error instead of returning bool.
   (...)
    301             If one or more modules found to be incompatible
    302     """
--> 303     ModuleValidator.validate(module, strict=True)

File ~\Miniconda3\envs\interpretml\lib\site-packages\opacus\validators\module_validator.py:72, in ModuleValidator.validate(cls, module, strict)
     70 # raise/return as needed
     71 if strict and len(errors) > 0:
---> 72     raise UnsupportedModuleError(errors)
     73 else:
     74     return errors

UnsupportedModuleError: [NotImplementedError("Model contains a trainable layer that Opacus doesn't currently support(:ConceptNAMNary(\n  (concept_dropout): Dropout(p=0.0, inplace=False)\n  (concept_nary_nns): ModuleDict(\n    (ord1_net0): ConceptNNNary(\n      (model): Sequential(\n        (0): Conv1d(8, 512, kernel_size=(1,), stride=(1,), groups=8)\n        (1): GroupNorm(32, 512, eps=1e-05, affine=True)\n        (2): ReLU()\n        (3): Conv1d(512, 512, kernel_size=(1,), stride=(1,), groups=8)\n        (4): GroupNorm(32, 512, eps=1e-05, affine=True)\n        (5): ReLU()\n        (6): Conv1d(512, 256, kernel_size=(1,), stride=(1,), groups=8)\n        (7): GroupNorm(32, 256, eps=1e-05, affine=True)\n        (8): ReLU()\n        (9): Conv1d(256, 8, kernel_size=(1,), stride=(1,), groups=8)\n      )\n    )\n  )\n)). Please implement and register grad sampler for this layer. (See opacus.grad_sample.utils.register_grad_sampler)")]
```
```

**Comment by ffuuugor** [comment]
Huh, this should not happen - it's an error in our validation code, thanks for helping us uncover that. Fix is coming shortly

**Comment by alexandresablayrolles** [comment]
Closing the issue as the PR has been merged. Feel free to reopen if the fix doesn't work.
