### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by qq648545022** [pytorch/opacus#460]
## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1.i used all the method that installing the opacus,but it raised "ModuleNotFoundError: No module named 'opacus.dp_model_inspector'"  when i used  the code like this ->from opacus.dp_model_inspector import DPModelInspector
2.
3.

**Comment by alexandresablayrolles** [comment]
The DPModelInspector does not exist anymore (it was in an old version of Opacus). It is now replaced by module validation directly in the GradSampleModule.

**Comment by qq648545022** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qq648545022** [comment]
thanks，after tyring  many version ，i fixd it
