### ISSUE TITLE
mismatch between the documentation and the behaviour of `make_private_with_epsilon`

### ISSUE THREAD

**Issue by omarfoq** [pytorch/opacus#467]
`PrivacyEngine.make_private_with_epsilon` does  not behave as explained by the documentation. In particular, `poisson_sampling` can not passed as an argument to this method. I think that the error is due to calling `get_noise_multiplier` (in accountants/utils.py) with `**kwargs`, but `RDPAccountant.get_epsilon` (in `rdp.py`) and  `GaussianAccountant.get_epsilon` (in `gdp.py`) only accepts a fixed number of arguments. Also, I think that the signature of GaussianAccountant.get_epsilon should be `get_epsilon(self, delta: float, poisson_sampling: bool = True) -> float`

**Comment by FrancescoPinto** [comment]
Actually the msimatch includes the impossibility of choosing the clipping strategy with `make_private_with_epsilon` (as the parameter is not passed correctly to `make_private`)
