### ISSUE TITLE
pytorch running error

### ISSUE THREAD

**Issue by ChenPen1** [pytorch/opacus#47]
Hello,when I used "pyhon mnist.py --device=cpu -n=15 --lr=.25 --sigma=1.3 -c=1.5 -b=250", there are some prolem. as follows:

TypeError: normal() received an invalid combination of arguments - got (int, Tensor, torch.Size, device=torch.device, generator=torch._C.Generator), but expected one of:
 * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, torch.Generator generator, Tensor out)
Thanks for your answer!

**Comment by karthikprasad** [comment]
Hello @ChenPen1 , could you paste the entire stack trace here? I was not able to reproduce this.

**Comment by ChenPen1** [comment]
Thank you for your answer. After reinstalling Pytorch, the problem was solved.
