### ISSUE TITLE
Model finetuning

### ISSUE THREAD

**Issue by timudk** [pytorch/opacus#477]
## 🚀 Feature
It would be nice to be able to only fine-tune a subset of the model parameters with Opacus. Currently this is not possible since there is a check that module parameters = optimizer parameters (https://github.com/pytorch/opacus/blob/5169ad2a892b5b49373f6727c723f66b510e5a3b/opacus/privacy_engine.py#L385)

**Comment by timudk** [comment]
I am actually curious about what's the purpose of this check in the first place.

**Comment by karthikprasad** [comment]
Hi @timudk , the check was motivated by the issue described in https://github.com/pytorch/opacus/issues/432
Your usecase makes sense, though. I think ensuring trainable parameters are same between model and optimizer rather than *all* parameters addresses this issue.
