### ISSUE TITLE
ZeroDivisionError when alpha = 1.0

### ISSUE THREAD

**Issue by Kritikalcoder** [pytorch/opacus#49]
In  _compute_rdp(q, sigma, alpha), the value of 

return _compute_log_a(q, sigma, alpha) / (alpha - 1)

becomes zero when alpha = 1.0, a valid value for alpha order.

**Comment by JohnlNguyen** [comment]
Hi, in our accountant RDP
the relaxation is (ε + (log(1 / delta) / alpha - 1), δ) hence the alpha orders has to be > 1.
