### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [32] at entry 0 and [1022] at entry 2

### ISSUE THREAD

**Issue by Simha55** [pytorch/opacus#505]
## 🐛 Bug

Hi I ran a transformer code using opacus and it was giving me runtime error. But when I run it without opacus it is running properly. could you please check the issue.
 Here is the notebook link: https://colab.research.google.com/drive/1fwK-5o5EUJEIWQMRg0m__cIyCy5_J-ij?usp=sharing

## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1.
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by alexandresablayrolles** [comment]
Thanks for raising the issue. From the looks of it, it is a problem of position of batch and sequence dimensions. Opacus assumes the first dimension is the batch dimension, but you seem to be playing with it by running 'permute' in your Transformer. This is the code I used to debug the issue:
```
print([(n, p.grad_sample.shape[0]) for (n, p) in model.named_parameters()])
```
It will show you which layers thought that the batch size was 1022 and which thought the batch size was 32.

**Comment by Simha55** [comment]
Could you please tell me where exactly you placed this code print([(n, p.grad_sample.shape[0]) for (n, p) in model.named_parameters()]) to debug. Since it is showing parameter name and None for me.

**Comment by alexandresablayrolles** [comment]
After executing your notebook and seeing the error, I created a new cell to put this code and run it.

**Comment by Simha55** [comment]
Hi, thanks a lot for helping me I changed the code and it solved the issue.

**Comment by anirban-nath** [comment]
Hi. I am having the same issue with a vision transformer that I am using. How did you change your code to fix this issue?

**Comment by Simha55** [comment]
Make sure batch size come first in dimension

**Comment by anirban-nath** [comment]
@Simha55 Thanks for the suggestion but like I saw in the source code, there is no batch_first attribute inside DPMultiHeadAttention. And if I do put my batch_size as the first dimension for "key", I get an error like: -

**Comment by Simha55** [comment]
Is it possible for you to share the notebook. Me or @alexandresablayrolles can check the error.
