### ISSUE TITLE
GDP Accountant get_epsilon method should not pop from history

### ISSUE THREAD

**Issue by kiddyboots216** [pytorch/opacus#535]
## 🐛 Bug

get_epsilon in the GDP accountant calls self.history.pop() which for obvious reasons is terrible. You can't iteratively check epsilon and then print it at the end of training, for example. 

## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1.
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ffuuugor** [comment]
This is very much true, thanks for bringing this to our attention.

@ashkan-software I think it'll be sufficient to replace `self.history.pop()` with `self.history[-1]`
