### ISSUE TITLE
A bug in the tutorial building_image_classifier.ipynb

### ISSUE THREAD

**Issue by mmalekzadeh** [pytorch/opacus#54]
According to the description of the `virtual_step(self)` method in the following line

https://github.com/pytorch/opacus/blob/d68b2bd28c55e8bb695b3a6eb3050c08fb3b484f/opacus/privacy_engine.py#L335

the command `optimizer.zero_grad()` should be called after a real step and not at each step.

In the current [tutorial](https://github.com/pytorch/opacus/blob/master/tutorials/building_image_classifier.ipynb),  the command `optimizer.zero_grad()`  is called for every step (real or virtual) which seems to be wrong.

https://github.com/pytorch/opacus/blob/d68b2bd28c55e8bb695b3a6eb3050c08fb3b484f/tutorials/building_image_classifier.ipynb#L372

This line (`optimizer.zero_grad()`) should be moved and placed right after `optimizer.step()`

**Comment by Darktex** [comment]
Yes, this looks like a bug. Thank you for reporting!
