### ISSUE TITLE
Privacy computation script throws error due to lacking keyword arguments

### ISSUE THREAD

**Issue by gkaissis** [pytorch/opacus#564]
It seems that the compute privacy script (https://github.com/pytorch/opacus/blob/main/opacus/scripts/compute_dp_sgd_privacy.py) was not updated with the keyword-only argument syntax so it throws an error from https://github.com/pytorch/opacus/blob/main/opacus/accountants/analysis/rdp.py 263 and 290 because they only accept keyword args.

**Comment by alexandresablayrolles** [comment]
Closing the issue as the PR has been merged.
