### ISSUE TITLE
DPMultiheadedAttention is not a full drop in replacement for nn.MultiheadAttention

### ISSUE THREAD

**Issue by jfb54** [pytorch/opacus#596]
## 🐛 Bug

Not only is the API missing the batch_first parameter (https://github.com/pytorch/opacus/issues/512), it is missing the in_proj_weight parameter. Thus it makes it impossible to use Opacus with a transformer.

## Expected behavior
Ability to access the in_proj_weight parameter so that it may be initialized.

## Environment
Opacus 1.4
PyTorch 2.01

**Comment by HuanyuZhang** [comment]
Thanks for reporting bugs. Will fix it and #512 to make it work.

**Comment by tranvansang** [comment]
I am facing the same issue. In addition to what described in the issue description, `forward()` call also lacks `is_causal` parameter.

**Comment by HuanyuZhang** [comment]
Closed this issue, since we launched fixes in (https://github.com/pytorch/opacus/pull/610).
