### ISSUE TITLE
ImportError: cannot import name 'DifferentiallyPrivateDistributedDataParallel' from 'opacus.layers' 

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [pytorch/opacus#597]
```
from opacus.layers import DifferentiallyPrivateDistributedDataParallel as DPDDP
ImportError: cannot import name 'DifferentiallyPrivateDistributedDataParallel' from 'opacus.layers' (/root/anaconda3/envs/LLM/lib/python3.11/site-packages/opacus/layers/__init__.py)
```

**Comment by lucamelis** [comment]
It's not an issue on v1.3.0+.
It seems like opacus has not been installed properly.

**Comment by karthikprasad** [comment]
Did the reinstallation work for you @Ethan-Chen-plus? If not, could you share a collab that reproduces this?

**Comment by Ethan-Chen-plus** [comment]
![image](https://github.com/pytorch/opacus/assets/84905965/5ab4029b-92a0-412e-9415-46f4f90364ed)

**Comment by karthikprasad** [comment]
@Ethan-Chen-plus , apologies, but I am not sure what to make of the above screenshot. Could you provide a link to a colab that I can run and reproduce the error?

**Comment by divyanshugit** [comment]
@Ethan-Chen-plus There has been a change in Opacus structure. The DPDDP thing has been moved out of `opacus.layers` to `opacus.distributed`. 
Now, you  can use:
```python
from opacus.distributed import DifferentiallyPrivateDistributedDataParallel as DPDDP
```

**Comment by HuanyuZhang** [comment]
I suppose you have solved the issue. Feel free to re-open it if you still need it.
