### ISSUE TITLE
'PRVAccountant' object has no attribute 'get_privacy_spent'

### ISSUE THREAD

**Issue by feigei12346** [pytorch/opacus#611]
## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1.AttributeError: 'PRVAccountant' object has no attribute 'get_privacy_spent'
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by HuanyuZhang** [comment]
Where is your code which triggers the error?

**Comment by HuanyuZhang** [comment]
close the issue due to not receiving response.
