### ISSUE TITLE
Why GDP and RDP give different result for the same config

### ISSUE THREAD

**Issue by huynhducloi00** [pytorch/opacus#643]
# gdp 
accountant=create_accountant(mechanism='gdp')
accountant.history = [(3, 0.2, 50)]
print( accountant.get_epsilon(delta=1/(60*800)))

==> result 1.83

# rdp 
accountant=create_accountant(mechanism='rdp')
accountant.history = [(3, 0.2, 50)]
print( accountant.get_epsilon(delta=1/(60*800)))
==> result 2.16

Shouldn't they be the same?

**Comment by HuanyuZhang** [comment]
No, they should not. Renyi DP is loose in accounting composed Gaussian mechanisms (https://arxiv.org/pdf/2106.08567.pdf).
