### ISSUE TITLE
Wrapper references can be easily replaced, consider using properties instead

### ISSUE THREAD

**Issue by andreatgretel** [pytorch/opacus#649]
(apologies for skipping template, not properly reporting a bug but rather suggesting an improvement)

Currently, the `DPOptimizer` passes through the `state`, `default` and `param_groups` attributes by simply [referencing them](https://github.com/pytorch/opacus/blob/32a465bfa980777e60a763616c83429785aa2ac6/opacus/optimizers/optimizer.py#L243). This can be an issue when another object tries to set these attributes from the outside, which might cause the reference to be replaced, instead of changing `original_optimizer`'s attributes. For instance, this happens when HF's `AcceleratedOptimizer` wraps the `DPOptimizer`, causing issues such as [this one](https://github.com/microsoft/dp-transformers/issues/43).

A safer alternative might be to do [what the `AcceleratedOptimizer` itself does](https://github.com/huggingface/accelerate/blob/6af157ea93dfbace1db88b0fdc7dfb568dfdd5a5/src/accelerate/optimizer.py#L85), using properties instead of passing by reference. For instance, for `param_groups`, that would look something like

```python
@property
def param_groups(self):
    return self.original_optimizer.param_groups

@param_groups.setter
def param_groups(self, param_groups):
    self.original_optimizer.param_groups = param_groups
```

## Reproducing etc.

Please take a look at [this Github issue](https://github.com/microsoft/dp-transformers/issues/43) to see a particular situation where passing by reference could become a problem. In summary: HF's accelerate will put yet another wrapper around the `DPOptimizer`, and ideally this "doubly-wrapped" optimizer should still function properly. However, due to the `AcceleratedOptimizer` attempt to change the whole `param_groups` attribute instead of its contents, changes will never get to the `original_optimizer`.

Consider the follow MWE of how this could happen
```python
from copy import deepcopy

import opacus
import torch

m = torch.nn.Linear(10, 1)
o = torch.optim.AdamW(m.parameters())
odp = opacus.optimizers.DPOptimizer(o, noise_multiplier=0.5, max_grad_norm=0.1, expected_batch_size=32)

pg = deepcopy(odp.param_groups)
pg[0]['lr'] = 1.0
odp.param_groups = pg

print('LR at DPOptimizer:', odp.param_groups[0]['lr'])
print('LR at original_optimizer:', odp.original_optimizer.param_groups[0]['lr'])
```

**Comment by HuanyuZhang** [comment]
Thanks for reporting this. We will investigate and launch a fix.

**Comment by iden-kalemaj** [comment]
Thanks again for reporting this. The issue has now been fixed.

**Comment by HuanyuZhang** [comment]
https://github.com/pytorch/opacus/pull/660
