### ISSUE TITLE
Unable to Adjust Alpha Range for Privacy Bound in Latest Version of Opacus

### ISSUE THREAD

**Issue by zedoul** [pytorch/opacus#670]
> UserWarning: Optimal order is the largest alpha. Please consider expanding the range of alphas to get a tighter privacy bound.

According to the [official Opacus documentation](https://opacus.ai/docs/faq#what-are-alphas), the privacy_engine.make_private_with_epsilon function should allow to specify a range of alphas to obtain tighter privacy bounds as follows:

> You can pass your own alphas by passing alphas=custom_alphas when calling privacy_engine.make_private_with_epsilon

However, it seems that this functionality is no longer available in the latest version.

**Comment by EnayatUllah** [comment]
Thanks for the pointer! You are right, the functionality is removed now. We will update the website accordingly.
