### ISSUE TITLE
Support bias correction when using Adam with DP

### ISSUE THREAD

**Issue by qiaoyuet** [pytorch/opacus#679]
## 🚀 Feature
Support bias correction when using the Adam optimizer with DP.

## Motivation

We hope to support the bias correction feature proposed in this paper: https://arxiv.org/abs/2312.14334. 

## Pitch

We are contributing a PR and would like suggestions on the implementation. Opacus supports DP optimizers by wrapping `DPOptimizer` around base optimizers from `torch.optim`. For our feature, we need to pass DP parameters (clipping norm, noise multiplier, and batch size when using Poisson samplers) to the base optimizer. Ideally, we’d avoid modifying DPOptimizer, but updating the base optimizer in `torch.optim` for a DP-specific feature feels inappropriate and we believe it’s better to keep it within Opacus. What’s the best practice for doing so?

Thanks.

**Comment by HuanyuZhang** [comment]
My gut feeling is that you can build a custom adam optimizer, which is inherited from the original adam optimizer (``torch.optim``), with the changes there. 
In using, replace the adam optimizer by the one you create, and wrap it by our ``DPOptimizer ``. Wdyt?
