### ISSUE TITLE
can I set some model parameter's requires_grad false after make_private

### ISSUE THREAD

**Issue by HuitongJin** [pytorch/opacus#687]
## 📚 Documentation

can I set some model parameter's requires_grad false after make_private

**Comment by iden-kalemaj** [comment]
Thank you for the question. Are you using [ghost](https://pytorch.org/blog/clipping-in-opacus/) clipping or vanilla DP-SGD? If using ghost clipping, then an error would prevent you from setting model parameter's to `requires_grad = False` after the call to `make_private`. We are working on fixing this issue. 

If using vanilla DP-SGD we do not expect an issue but would encourage testing to see if an error arises.

**Comment by iden-kalemaj** [comment]
I will close the issue due to inactivity, but feel free to re-open it if there are follow-up questions. Thank you!
