### ISSUE TITLE
error when batch_size  is greater than sample_size.

### ISSUE THREAD

**Issue by mmalekzadeh** [pytorch/opacus#74]
If `q` is 1 then the following line has to calculate `log(0)` which raises `ValueError: math domain error`:
https://github.com/pytorch/opacus/blob/6b41f601816f00fa1a5896f19e6c3654a8d1fa10/opacus/privacy_analysis.py#L146

In fact, `q` is the `sample_rate` in this line:
https://github.com/pytorch/opacus/blob/6b41f601816f00fa1a5896f19e6c3654a8d1fa10/opacus/privacy_engine.py#L83

Is there any theoretical reason that `sample_rate` cannot be 1? I know it is rare, but is it forbidden at all?

if there might be a situation where one can set `sample_rate=1`,  isn't it better to handle this with an exception?

**Comment by sayanghosh** [comment]
Hi @mmalekzadeh for privacy accountant RDP ``0 < q < 1`` is needed else it is not possible to compute the privacy budget. Thus we need to have the ``sample_rate`` between 0 and 1. [https://github.com/pytorch/opacus/blob/6b41f601816f00fa1a5896f19e6c3654a8d1fa10/opacus/privacy_analysis.py#L182](url). We will be handling this with an exception shortly.

**Comment by karthikprasad** [comment]
Hi @mmalekzadeh , can you share the entire script you are running? When sample_rate is 1, this line should be triggered. https://github.com/pytorch/opacus/blob/6b41f601816f00fa1a5896f19e6c3654a8d1fa10/opacus/privacy_analysis.py#L228

**Comment by mmalekzadeh** [comment]
Hi @karthikprasad. Thanks for pointing this out. 
OK, I apologize because when I checked more it wasn't the `sample_rate` problem.

It was a problem with the `virtual_batch_size` which was chosen more than `sample_size`, so my fault.

Still, it may be helpful if it could raise an exception. Here I just put a script to reproduce the error.
```
from torchvision import models
from opacus import PrivacyEngine
privacy_engine = PrivacyEngine(
                models.alexnet(),
                batch_size = 8,
                sample_size = 4,
                alphas=[1 + x / 10.0 for x in range(1, 100)] + list(range(12, 64)),
                noise_multiplier = .5,
                max_grad_norm =  1.)
privacy_engine.get_privacy_spent(1e-3)
```
And Error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-12-cff4b1452935> in <module>()
      8                 noise_multiplier = .5,
      9                 max_grad_norm =  1.)
---> 10 privacy_engine.get_privacy_spent(1e-3)

6 frames
/usr/local/lib/python3.6/dist-packages/opacus/privacy_analysis.py in _compute_log_a_for_frac_alpha(q, sigma, alpha)
    168     i = 0
    169 
--> 170     z0 = sigma ** 2 * math.log(1 / q - 1) + 0.5
    171 
    172     while True:  # do ... until loop

ValueError: math domain error
```

**Comment by karthikprasad** [comment]
No problem @mmalekzadeh. `batch_size > sample_size` should also be covered when you construct a PrivacyEngine object. https://github.com/pytorch/opacus/blob/master/opacus/privacy_engine.py#L90

This check was added less than 2 weeks ago. Perhaps you are on an older commit?

**Comment by mmalekzadeh** [comment]
In fact, I am using Colab and using exactly this:
```
!pip install torchcsprng==0.1.2+cu101 torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install opacus
from torchvision import models
from opacus import PrivacyEngine
privacy_engine = PrivacyEngine(
                models.alexnet(),
                batch_size = 8,
                sample_size = 4,
                alphas=[1 + x / 10.0 for x in range(1, 100)] + list(range(12, 64)),
                noise_multiplier = .5,
                max_grad_norm =  1.)
privacy_engine.get_privacy_spent(1e-3)
```
but the same error!

**Comment by karthikprasad** [comment]
@mmalekzadeh , Yes, the above fix I mentioned went in after the previous release. It should reflect in the next release (v0.9.2)
