### ISSUE TITLE
problem about download opacus

### ISSUE THREAD

**Issue by wlnancy** [pytorch/opacus#75]
##  Feature
I try to download opacus but there exists problem that I can't solve. Here is the error:

ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from opacus) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.6.0 (from opacus)
I have download torch1.6.0 . Is the version is not matched? What version of torch and torchversion should I change to?

**Comment by karthikprasad** [comment]
Hi! Could you share more details on how you downloaded this? I tried `pip install opacus` and it works fine.

**Comment by wlnancy** [comment]
Yeah, I install it use the comment " pip install opacus". Then it occurs the error mentioned above. I have tried to change the version of torch I used, but that doesn't seem to work.

**Comment by karthikprasad** [comment]
That is very strange. I wonder if this is an environment issue.
* Are you seeing this on Google Colab with GPU? If yes, you'll have to install it this way: https://opacus.ai/docs/faq#how-do-i-run-opacus-in-colab
* If you are seeing this on local machine with a different CUDA version: you'll have to install torch accordingly as mentioned in pytorch.org
* If you are seeing this on a CPU machine, can you share the details of your environment?

**Comment by wlnancy** [comment]
I have install CUDA10.2、torch1.5.1 and torchversion0.6.1. But the problem still exists. I don't know what the problem is.

**Comment by karthikprasad** [comment]
Can you please share your environment details. It is really hard to debug without it.

**Comment by wlnancy** [comment]
I use python37 in  window10. And I use pycharm to programme. I have installed CUDA10.2、torch1.5.1 and torchversion0.6.1. I try to install opacus using 'pip install opacus' and it occurs some errors. This is my current environment, do you need some other information?

**Comment by karthikprasad** [comment]
That is weird! Could you try updating your pip and pytorch once?
```
pip install --upgrade pip
pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by wlnancy** [comment]
I have installed the package you mentioned above, and then I try to install opacus using 'pip install opacus' but it occurs error:
ERROR: Could not find a version that satisfies the requirement torchcsprng==0.1.2 (from opacus) (from versions: none)
ERROR: No matching distribution found for torchcsprng==0.1.2 (from opacus)
And I try to install torchcsprng==0.1.2 by using 'pip install torchcsprng==0.1.2' ,but it still exists error:
ERROR: Could not find a version that satisfies the requirement torchcsprng===0.1.2 (from versions: none)
ERROR: No matching distribution found for torchcsprng===0.1.2
Do you know how to resolve it?

**Comment by karthikprasad** [comment]
So I take that the error regarding  pytorch is now resolved?

The error regarding csprng also looks similar to me. You’d probably need specify the `-f https://....` part you did in the above command while installing on windows.
```
pip install torchcsprng torch -f https://download.pytorch.org/whl/torch_stable.html
```

Note that csprng is not yet supported for CUDA on Windows. (https://github.com/pytorch/csprng)

**Comment by wlnancy** [comment]
Thanks, I download opacus successfully under your suggestion. By the way,do you know how to solve the error:
OSError: [WinError 126]The specified module could not be found.Error loading "D:\Program Files\Python\Python37\lib\site-packages\torch\lib\asmjit.dll" or one of its dependencies.
When I run the example, it occurs this error.

**Comment by karthikprasad** [comment]
That’s good to know. Unfortunately, I don’t know much about this latest error. Looks like some windows specific issue for pytorch. I’d suggest you post this in pytorch discussions forum. 

I’ll close this task now as opacus installation now works.
