### ISSUE TITLE
Question regarding "momentum"?

### ISSUE THREAD

**Issue by YongGuCheng** [pytorch/opacus#77]
Dear All,

When I read the cifar10 example (https://github.com/pytorch/opacus/blob/master/examples/cifar10.py), I notice that the "SGD momentum = 0.9" is used. 
My question is, does the use of "SGD momentum = 0.9" have impact on the privacy analysis?

**Comment by ilyamironov** [comment]
No, it has no impact on privacy analysis. Opacus is compatible with all first-order optimizers (those that need only the average gradient over a batch) and it is oblivious to how these optimizers are parameterized.

**Comment by YongGuCheng** [comment]
> No, it has no impact on privacy analysis. Opacus is compatible with all first-order optimizers (those that need only the average gradient over a batch) and it is oblivious to how these optimizers are parameterized.

Got it. Thank you @ilyamironov
