### ISSUE TITLE
Effect of constant batch size to the privacy calculation

### ISSUE THREAD

**Issue by BurakHasircioglu** [pytorch/opacus#80]
It seems the privacy calculation of sampled mechanisms in Opacus is done based on https://arxiv.org/abs/1908.10530. In this paper, it is assumed that each element is sampled independently with probability q. That means we can have different batch sizes for each iteration though average batch size is qN, where N is the total number of elements in the dataset. However, in the examples under https://github.com/pytorch/opacus/tree/master/tutorials, a constant batch size is used. This may violate the independence assumption. Simply, given qN elements are already chosen, the probability of any other sample being chosen is zero, instead of q. I wonder if the analysis in the paper is still valid in constant batch size. If not, then doesn't using constant batch size underestimate the privacy spent?

**Comment by tholop** [comment]
I have the same question. For reference, here is a similar issue in Tensorflow Privacy: https://github.com/tensorflow/privacy/issues/19#issuecomment-49757633. This paper, that analyses subsampled Gaussian mechanism with fixed batch size, might be useful as well: https://arxiv.org/abs/1808.00087.

**Comment by ilyamironov** [comment]
@BurakHasircioglu and @tholop are both right. Our current analysis is a shortcut, which assumes Poisson sampling of minibatches. We may consider integrating the work of Wang et al. referenced by @tholop into Opacus, especially if there's support for it in the community.

**Comment by ashkan-software** [comment]
Closing this issue. If anyone feels like we have not addressed this, please feel free to re-open :)
