### ISSUE TITLE
upgrade to 0.10.0 fails in python 3.8.5 environment

### ISSUE THREAD

**Issue by pepper-jk** [pytorch/opacus#91]
##  Bug

I tried `pip install opacus==0.10.0` in my python 3.8.5 conda env and got the following error:

```
ERROR: Could not find a version that satisfies the requirement dataclasses==0.7 (from opacus==0.10.0) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.7 (from opacus==0.10.0)
```

`dataclasses==0.7` seems to be unavailable.

## Alternative

I tried to install `opacus==0.10.0` in a new and clean environment to be sure, same result.

## Additional context

First discussed in issue #88 .

**Comment by pepper-jk** [comment]
Okay, I found that `dataclasses==0.7` is only available for python 3.6.
I will try a python 3.6 environment.

source: https://pypi.org/project/dataclasses/

**Comment by ffuuugor** [comment]
Thanks for the reporting! I can indeed reproduce the problem.
The issue has to do with our deployment process, fix is on the way

**Comment by ffuuugor** [comment]
This should be fixed now
