### ISSUE TITLE
Support for 3DConv layers

### ISSUE THREAD

**Issue by Daniel-Wu** [pytorch/opacus#92]
##  Feature
We would like opacus to support 3D conv layers for differentially-private training of video action recognition models. 

## Context
Looking at the code in
```https://github.com/pytorch/opacus/blob/master/opacus/supported_layers_grad_samplers.py```
I originally thought the implementation of 3D conv would be identical to that of 2D conv. Unfortunately, my naive implementation throws ```RuntimeError: Input Error: Only 4D input Tensors are supported (got 5D)``` during training. Is there a simple fix, or is there something deeper at play here?

**Comment by Darktex** [comment]
We are going to need a repro for this :) 

In general, the error you are getting does not surprise me: if you want to run a 4D conv over a video, your input had better be 5D: [batch_size, color, time, height, width]. If you have batch_size=1, you still need to unsqueeze just like 2d convs need 3d inputs all the time.

See also the docs: https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html

**Comment by ffuuugor** [comment]
I don't think we need a repro for this - we explicitly don't support Conv3d layers at the moment.

The reason implementation for 3D is not trivial compared to 2D is `torch.nn.functional.unfold` method we use in grad sample computation. It only supports 4D tensors as input - kind of tensors you get for Conv2d ([batch_size, channels, height, width]).
There's no fundamental reason it should be like this, it's just a matter of implementation.

We're working on this and hope to provide the support soon.

**Comment by ffuuugor** [comment]
This should work now, let us know if it doesn't work for you.
