### ISSUE TITLE
Can't install opacus with: pip install opacus

### ISSUE THREAD

**Issue by pfreitasaf** [pytorch/opacus#97]
pip install opacus
**ERROR: Could not find a version that satisfies the requirement opacus (from versions: none)
ERROR: No matching distribution found for opacus**

My configurations:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

python --version
Python 3.6.2 :: Anaconda, Inc.

import torch
print(torch.__version__)
1.6.0

**Comment by karthikprasad** [comment]
Hello @pfreitasaf, I see that your platform is using Python 3.6.2. Opacus requires python 3.6.9 or higher.
