### ISSUE TITLE
Citation key for Opacus

### ISSUE THREAD

**Issue by tholop** [pytorch/opacus#98]
Please, do you have a preferred citation method for this repository? 
So far, academic papers seem to refer to the URL of this repository or to `https://opacus.ai`, with Facebook as the author.
In case you are interested, some scientific libraries use this: https://guides.github.com/activities/citable-code/

**Comment by ilyamironov** [comment]
Thank you for the proposal! Unfortunately, Zenodo requires third-party access for the entire repo, and it looks like PyTorch is not supporting it at this point.

Even without DOI, I suggest the following style of citing Opacus:
```
@misc{Opacus, 
  title = "{O}pacus {PyTorch} library", 
  howpublished = "Available from \href{https://opacus.ai}{opacus.ai}",
  key = "Opacus"
}
```

**Comment by tholop** [comment]
Thank you!
